Keyfactor/ejbca-ce

- modules/admin-gui/resources/languages/languagefile.en.properties
Fixes are:
* Typo/error (e.g. punctuation, etc.)
* File code syntax (e.g. double CR before big section starting with `###`)
* Ambiguous term 'Issued' in message 'Certificates Issued Not [Before/After]'
* Moving of 'OAuth Key Management' subsection (in this right big section)
**Note:** all the messages `Certificates Issued Not [Before/After]` had been replaced by the better messages from the online documentation, _i.e._ `Certificate Validity Not [Before/After]`.
Reference: https://doc.primekey.com/ejbca/ejbca-operations/ejbca-ca-concept-guide/validators-overview/key-validators#KeyValidators-CommonKeyValidatorSettingsCommon_Key_Validator_Settings
> English l10n fixes proposal for the main branch (future 7.5)

- modules/cesecore-common/src-test/org/cesecore/util/StringToolsTest.java
- modules/cesecore-common/src/org/cesecore/util/StringTools.java
Fixes a bug in handling of Unicode string length. Using characters outside the ASCII range in an end entity password caused the following error:
```txt
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 40
at deployment.ejbca.ear//org.cesecore.util.StringTools.obfuscate(StringTools.java:626)
at deployment.ejbca.ear//org.ejbca.core.ejb.ra.UserData.setOpenPassword(UserData.java:499)
at deployment.ejbca.ear.ejbca-ejb.jar//org.ejbca.core.ejb.ra.EndEntityManagementSessionBean.setPassword(EndEntityManagementSessionBean.java:1510)
at deployment.ejbca.ear.ejbca-ejb.jar//org.ejbca.core.ejb.ra.EndEntityManagementSessionBean.setClearTextPassword(EndEntityManagementSessionBean.java:1451)
```
> Fix obfuscating non-ASCII passwords

- doc/howto/mysql-privileges.sh
This is required for supporting databases named something like "prefix_ejbca".
> Remove hardcoded DB name in mysql-privileges.sh

- build.xml
The Hardware Token feature had been removed from EJBCA project since a long time ago.
When build the project, the folder `hwtoken` is created, and stay empty.
In order to clean the old code, old traces of “hwtoken” had been removed (_i.e._ in `build.xml` file).
An `ant clean` command doesn't remove the folder `hwtoken` from project root folder.
By safety, the old following line can be revert (as you want):
`		    	<exclude name="hwtoken/**" />`
> Cleaning: Remove old hwtoken traces

- modules/admin-gui/resources/languages/languagefile.en.properties
- modules/admin-gui/resources/languages/languagefile.fr.properties
- modules/admin-gui/resources/sysconfig/editautoenrollmentconfiguration.xhtml
Some field information (i.e. 'title' HTML tag) are bugged: bad message key, bad description, etc.
For better usability, in Admin GUI, these had been fixed.
It's a minor fix, but easy to review! ;-)
> MS Auto-Enrollment: Fix field format information in GUI

- modules/ejbca-ejb/src/org/ejbca/core/ejb/ca/auth/EndEntityAuthenticationSessionBean.java
Fix implicit cast from int to Long that does not return valid results for the maximumExpirationDate, and therefore the configuration of Allow Renewal Before Expiration does not work properly.
> Fix calculation of maximumExpirationDate to renew certificate

- modules/ra-gui/resources/WEB-INF/classes/Messages_ar.properties
- modules/ra-gui/resources/WEB-INF/classes/Messages_de.properties
- modules/ra-gui/resources/WEB-INF/classes/Messages_en.properties
- modules/ra-gui/resources/WEB-INF/classes/Messages_sv.properties
- modules/ra-gui/resources/WEB-INF/classes/Messages_vi.properties
Just add some metadata in comments in RA language files, such as: Language name, Language code, Encoding.
It's easier to identify the right language file, than only the simple code in filename. That's all. No more, no less!
> L10n: Language metadata added in RA language files (in comments)

- modules/ra-gui/resources/WEB-INF/classes/Messages_en.properties
Add the missing message "RFC9336 Document Signing" (OID: 1.3.6.1.5.5.7.3.36) in RA GUI English language file
> L10n: Add Document-Signing EKU in RA GUI (English)

- modules/ra-gui/resources/resources/component/eedetails.xhtml
`<h:commandButton>` gets rendered as `<input type=submit>`. Pressing the Enter key in an input field on an form with multiple submit buttons is equivalent to clicking the first one. Up to now, the default action of the Edit End Entity form was the dangerous operation "Revoke certificates and delete end entity." It is probably more likely that the user intended to save changes instead, which is the action that is now the default (executed when pressing Enter).
This fixes #430. The new button order looks like this:
> Edit End Entity: reorder buttons, so Revoke And Delete is not the default action

- modules/admin-gui/resources/languages/languagefile.en.properties
Some fixes for Admin GUI English, from version 8.2.0.
Remarks:
- UID means "User identifier", not "Unique ID"
- EKU_MS_CA_EXCHANGE is a usage not an object: replace "MS CA Key Exchange Certificate" by "MS CA Key Exchange"
- minor typos
> L10n: Admin GUI English fix (from version 8.2.0)

- modules/admin-gui/resources/ra/addendentity.jsp
The "Add End-Entity" web page (from Admin GUI) has lost its favicon!
Action: Add back the favicon of the "Add End-Entity" web page.
> Fix: Add back favicon to Add End-Entity web page (in Admin GUI)

- modules/ra-gui/resources/enrollmakenewrequest.xhtml
In RA GUI, function Make Request, section "Required Subject Directory Attributes", there is a display bug (and HTML 'label' bug) with Required and Non Modifiable SDA attributes.
And, when click on a Required and Non Modifiable selectable list SDA attribute name, there is no focus on the list.
Screenshot **with the bug**
Screenshot **with the fix**
**Reproduce:**
- create Certificate Profile with Subject Directory Attributes (SDA) checked
- create End-Entity Profile with Subject Directory Attributes (SDA): **Required** and **Non Modifiable** (with fixed text 'Hello', or selectable list 'Toto;Titi', is the same bug)
- go to RA GUI > Make Request
- select the End-Entity Profile above, then look at SDA bug
**Info:**
To fix it (duplication bug, and focus bug), I used a similar code than …
> Fix: RA GUI Make Request - Bug with Focus and Duplication

- modules/ejbca-common/src/org/ejbca/core/model/ra/EndEntityInformationFiller.java
- modules/ejbca-ejb/src-test/org/ejbca/core/model/ra/EndEntityInformationFillerTest.java
Noticed some issues when importing certificates which included SANs. The EE Policy I was using had the 'Allow Merge DNs across all interfaces" activated. I thought this setting only affected the Subject DN, but it turns out it also affects SANs (Note: This should be mentioned in the documentation).
The error when importing a certificate was:
ERROR: org.ejbca.core.model.ra.raadmin.EndEntityProfileValidationException: Wrong number of DNSNAME fields in Subject Alternative Name.
There is a DEBUG message that helped to understand the issue:
DEBUG [org.ejbca.core.model.ra.EndEntityInformationFiller] (default task-5) merged dn: DNSNAME=test.org.au,dNSName=test.org.au
Note that 'merged dn' has two entries with the same value, but one is referenced/keyed as "DNSNAME" and the other "dNSName".
The …
> Fix merge DNs with SANs

- modules/ra-gui/resources/css/ra.css
- modules/ra-gui/resources/enrollmakenewrequest.xhtml
Better default CSS style for Make New Request page, in RA GUI.
**Features:**
- use of the full width of the page
- the input fields are wider: better to check input values
- all the main input fields are in center of the page, and vertical aligned
- all the field label are in one, or two lines (note: one line in future contribution)
- like the Pure CSS base, it's still a responsive design
- I only modified the default '`ra.css`' file: so, admins always can customize CSS with the '`w_e_styles.css`' file
- fix the text '_Use Entity CN Field_' in white (it was unreadable in black color)
- tested with Firefox, and Chrome
> Improve: RA GUI Make New Request page CSS

- src/upgrade/650_660/650_660-upgrade-mssql2000.sql
- src/upgrade/790_7100/790_7100-upgrade-mssql2000.sql
change sql syntax from
ALTER TABLE ApprovalData MODIFY subjectDn VARCHAR(400); for mysql
to
ALTER TABLE ApprovalData ALTER COLUMN subjectDn VARCHAR(400); for mssql
in 790_7100-upgrade-mssql2000.sql
I don't know how to create JUnit test case for this change, please contact me if needed.
> Fix: fix sql syntax error in sql upgrade file for 790_7100

- modules/ejbca-ejb/src/org/ejbca/core/ejb/ca/caadmin/CAAdminSessionBean.java
- modules/systemtests/src-test/org/ejbca/core/ejb/ca/caadmin/RenewCATest.java
It is possible to get EJBCA to renew a CA using a different signing key algorithm (ie., RSA to ECDSA). The steps required are:
1. Create a new EC key on the CA's CryptoToken (assuming a move from RSA to ECDSA)
2. Set the CryptoToken's Signature Algorithm to use ECDSA. This can be done using the Command Line Interface. (Potentially, this step could be handled by an appropriate code change)
3. Set the Certificate Profile to use ECDSA-based Signature Algorithm.
4. Do the CA Renewal
These steps work well, but not if the Link Certificate is required. The Link certificate needs to be signed using the CA's previous signature algorithm, and the changes to the CryptoToken and the Certificate Profile affect the Link certificate generation.
Code changes are required to detect when a CA's key …
> Fix to issue Link Certificate using previous Signature Algorithm

- modules/admin-gui/resources/languages/languagefile.en.properties
- modules/admin-gui/resources/languages/languagefile.fr.properties
Fix, and improve some language messages for ACME, in English, and in French languages.
Remarks:
- Unity "ms" is better than the word "Number"
- "Approval" is better than "Require approval" because the field is a drop down list of Approval profiles (not a checkbox)
> L10n: Admin GUI language fix (ACME)

- modules/ejbca-ejb-cli/src/org/ejbca/ui/cli/roles/RemoveAdminCommand.java
Fixed one error in the help text of the `removeadmin` command and harmonized the interpunction
n/a
> Fix help text for "removeadmin" command of CLI

- modules/ejbca-ejb-interface/src/org/ejbca/core/ejb/upgrade/UpgradeSessionLocal.java
- modules/ejbca-ejb/src/org/ejbca/core/ejb/upgrade/UpgradeSessionBean.java
The problem can be reproduced with MySQL or MariaDB when performing the post-upgrade to EJBCA v8.3.2 from an older EJBCA database version (older than v7.4) where the indexes `crldata_idx3` or `crldata_idx4` exist.
The following code obtains metadata locks over the CRLData table:
https://github.com/Keyfactor/ejbca-ce/blob/743f665e3749d4800509c76044aaac9d983790b4/modules/ejbca-ejb/src/org/ejbca/core/ejb/upgrade/UpgradeSessionBean.java#L1920
Then, the following call to the business method `UpgradeSessionBean.upgradeIndex` (which is invoked in a new transaction context) hangs up and the post-upgrade cannot complete. Using `SHOW FULL PROCESSLIST` you can find something like this running forever:
```
24,root,172.17.0.1:55646,ejbca,Query,9,Waiting for table metadata lock,DROP INDEX crldata_idx3 …
```
> Post-upgrade hangs when `crldata_idx3` or `crldata_idx4` exist

- modules/ra-gui/resources/css/ra.css
- modules/ra-gui/resources/css/w_e_style.css
- modules/ra-gui/resources/enrollmakenewrequest.xhtml
- modules/ra-gui/resources/resources/component/eedetails.xhtml
OLD REF: PR #551
**Changes > Make New Request (CSS align):**
- CSS horizontal align for 'Make New Request' page (like PR #512): for Token, Name Constraint Attributes, Other Certificate Data, and Other Data
- Bug: when only "Name Constraints, Excluded" is checked without "Name Constraints, Permitted", the title "Name Constraint Attributes" is not displayed
- Better CSS usage: modify HTML source (with adding style, and div) is better than modify CSS style. So I revert a part of my own CSS contribution (PR #512)
- now the CSS is more clear, with less default override, and more readability. So, now it's easier to override '`ra.css`'
- H3 in bold is really better, and more readable. I just removed the override from the CSS '`w_e_style.css`' (and keep the default bold feature from '`ra.css`')
- …
> Fix: RA GUI layout (CSS align, SDA bug, Search improv)

- modules/ejbca-ejb/src/org/ejbca/core/ejb/ra/EndEntityManagementSessionBean.java
- src/java/dncomponents.properties.sample
The default attributes order in `com.keyfactor.util.certificate.DnComponents#dNObjectsForward` is different to the sample order provided in `src/java/dncomponents.properties.sample`.
This can lead to unexpected behavior, e.g. when a user simply copies `dncomponents.properties.sample` to `src/java/dncomponents.properties` and performs only a minor modification to the file expecting only the effect of his changes, but instead, he suddenly starts getting other attributes in a different order, which can be quite confusing, at least.
The current PR patches syncs the order in `dncomponents.properties.sample` with `DnComponents#dNObjectsForward`.
Finally, a comment should be left for developers in the (non-publicly available) source for the field …
> Keep `dncomponents.properties.sample` in sync with `DnComponents#dNObjectsForward`

- modules/admin-gui/src/org/ejbca/ui/web/admin/endentity/EditEndEntityMBean.java
Using the AdminWeb (via RA function), updating the password for an End Entity does not work. A similar operation using the RAWeb is OK.
Identified an IF statement in EditEndEntityMBean.java that will set the password to null when regeneration is not being used. This overrides the actual password value being set by the Operator.
Manually testing using AdminWeb.
- [X ] I have performed a self-review of my code
- [X ] I have kept the patch limited to only change the parts related to the patch
> Cannot update EE password using AdminWeb

- .github/pull_request_template.md
- README.md
Added the OpenSSF Badge back to the README. 
https://www.bestpractices.dev/en/projects/9419
Added OpenSSF badge back to the README, linking to the EJBCA OpenSSF Best practices page: https://www.bestpractices.dev/en/projects/9419 
Please make sure that this badge remains in the README for the next release. 
Also fixed the link to the CONTRIBUTING Guidelines in the PR template. 
-
See also [Contributing Guidelines](https://github.com/Keyfactor/ejbca-ce/blob/main/CONTRIBUTING.md).
> Added OpenSSF Badge in README.md

- modules/ejbca-common-web/src/org/ejbca/util/mail/MailSender.java
It is useful to log recipient for the MailSender for tracking purposes. Similar behaviour was implemented in `EndEntityManagementSessionBean` but removed in https://github.com/Keyfactor/ejbca-ce/commit/730b5400ae838f019f1d67abf93ffcbd4da42bf0.
This PR adds information about recipients into the log.
> Log recipients for MailSender

- modules/ejbca-common-web/src/org/ejbca/core/protocol/cmp/CmpResponseMessage.java
…since it is not used to "uniquely identify a key" as stated in RFC 4210 5.1.1. Contributed under SPDX "LGPL-2.1-or-later".
[RFC 4210 5.1.1](https://www.rfc-editor.org/rfc/rfc4210#section-5.1.1) describes the purpose of CMP's `PKIMessage.PKIHeader.senderKID`.
For PBE/PBMAC1, EJBCA CE only uses this as a courtesy in `CmpMessageHelper.protectPKIMessageWithPBMAC1(...)` to help a client distinguish between protection keys when present in the request.
```text
These fields MUST be used if required to uniquely identify a key
(e.g., if more than one key is associated with a given sender name)
and SHOULD be omitted otherwise.
```
Shared secret bootstrap use-case where CMP clients gets a cert and trust anchor in IP.
CMP config:
* RA mode
* HMAC authentication module with "Specify secret"
* Random …
> Make PKIMessage.PKIHeader.senderKID optional for PBE/PBMAC1
