Keyfactor/ejbca-ce

modules/admin-gui/resources/languages/languagefile.fr.properties
src/intresources/ejbcaresources.fr.properties
src/intresources/intresources.fr.properties

**Admin-GUI French language fully translated, 100 %** (Community and Enterprise editions).
Updates are:
* Big update from SVN trunk to the branch 7.4.3 (about 150 messages)
* Replace 'LCR' by 'CRL'
* Fixes for Validators module
* Add "OAuth Key Management" messages
* Then remaining update from the branch 7.4.3 to the main branch (about 45 messages)

L10n: French updates for the main branch (big updates from 2020 SVN trunk & some fixes)

---

modules/admin-gui/resources/languages/languagefile.en.properties

Fixes are:
* Typo/error (e.g. punctuation, spaces, etc.)
* Update/add some comments
* Remove duplicate key
* Move 'External Account Bindings' subsection (in this right big section, i.e. System Configuration)

L10n: English fixes for the main branch (7.10.0.2)

---

modules/admin-gui/resources/ca/cafunctions.xhtml
modules/admin-gui/resources/languages/languagefile.en.properties
modules/admin-gui/resources/languages/languagefile.fr.properties
modules/admin-gui/resources/languages/languagefile.zz.properties
modules/admin-gui/resources/sysconfig/acmealiasconfiguration.xhtml
modules/admin-gui/resources/sysconfig/autoenrollconfiguration.xhtml
modules/admin-gui/resources/sysconfig/editautoenrollmentconfiguration.xhtml

Several fixes, about:
* MS Auto-Enrollment
* OAuth Key Management
* ACME protocol
* CA Structure & CRLs
References (MS Auto-Enrollment):
* https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/ktpass
* https://learn.microsoft.com/en-us/archive/blogs/pie/all-you-need-to-know-about-keytab-files
* https://web.mit.edu/kerberos/krb5-1.12/doc/basic/keytab_def.html
* https://web.mit.edu/kerberos/krb5-1.12/doc/admin/conf_files/krb5_conf.html

L10n: English fixes for the main branch (based on 7.10.0.2)

---

modules/admin-gui/resources/languages/languagefile.fr.properties

A lot of updates, about:
* MS Auto-Enrollment
* OAuth Key Management
* ACME protocol
* Azure CRL Publisher
* Intune Certificate Revocation
* C-ITS certificates
* CA Structure & CRLs
Note: the rebase had been squashed.
References (MS Auto-Enrollment):
* https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/ktpass
* https://learn.microsoft.com/en-us/archive/blogs/pie/all-you-need-to-know-about-keytab-files
* https://web.mit.edu/kerberos/krb5-1.12/doc/basic/keytab_def.html
* https://web.mit.edu/kerberos/krb5-1.12/doc/admin/conf_files/krb5_conf.html

L10n: French updates for the main branch (based on 7.10.0.2) Fully translated

---

bin/batchenrollmentgui.sh
bin/extra/cronverify.sh
bin/extra/sign-verify.sh
bin/nCipherHSM.sh
bin/nCipherJboss.sh
bin/pkcs11HSM.sh

Just linted the bash scripts. Use it or not. :-)

Linted the bash scripts

---

modules/admin-gui/src/org/ejbca/ui/web/admin/configuration/WebLanguagesImpl.java

When [adding a plugin to EJBCA](https://doc.primekey.com/ejbca/tutorials-and-guides/modifying-ejbca/creating-plugins) it is currently not possible to add a separate languagefile for your plugin.
Make it possible to bundle languagefiles with the plugin jar like this:
```
myjar.jar
|
+-- com/
|     |
|     +-- example/
|           |
|           +-- MyPlugin.class
|
+-- languages/
|     |
|     +-- languagefile.en.properties
```
EJBCA will then pick up the language strings in languagefile.%lang.properties and append them to the language file provided in the ear.

Load language files bundled with publisher plugins

---

modules/admin-gui/resources/languages/languagefile.fr.properties
src/intresources/ejbcaresources.fr.properties
src/intresources/intresources.fr.properties

Updates according to English language (v7.11.0)

L10n: French updates for the main branch (based on 7.11.0) Fully translated

---

modules/admin-gui/resources/languages/languagefile.fr.properties
src/intresources/ejbcaresources.fr.properties
src/intresources/intresources.fr.properties

A lot of language updates, about:
* DN attributes (Matter, UID, uniqueIdentifier, CertificationID)
* ACME protocol
* EST protocol
* MSAE
* Publishers
* Etc.

L10n: French updates for the main branch (based on 8.0.0) Fully translated

---

modules/admin-gui/resources/languages/languagefile.en.properties

L10n: English fixes for the main branch (typo)

---

CONTRIBUTING.md
README.md

Added file CONTRIBUTING.md. 
Updated link in README.

Add CONTRIBUTING guidelines

---

modules/ejbca-ejb/src/org/ejbca/core/protocol/cmp/RevocationMessageHandler.java
src/internal.properties

Fix cmp header sender field sorting

---

modules/admin-gui/resources/languages/languagefile.fr.properties

Full update (and some fixes) of French Admin GUI for version 8.2.0.

L10n: Admin GUI French update (based on 8.2.0) Fully translated

---

conf/web.properties.sample
modules/ejbca-common/src/org/ejbca/config/WebConfiguration.java
propertyDefaults.xml
src/java/defaultvalues.properties

Remove old traces of the Public Web interface.
It’s a minor issue.

Task: Remove some Public Web GUI old traces

---

modules/admin-gui/resources/languages/languagefile.fr.properties

Some French typo fixes. Thanks

L10n: Admin GUI French fix (typo)

---

modules/admin-gui/resources/languages/languagefile.fr.properties

Full update (and some fixes) of Admin GUI French, for v8.3.2, since v8.2.0.

L10n: Admin GUI French update (based on 8.3.2) Fully translated

---

modules/admin-gui/resources/languages/languagefile.de.properties
modules/admin-gui/src/org/ejbca/ui/web/admin/BaseManagedBean.java
modules/cesecore-common/src-test/org/cesecore/util/QueryCriteriaTest.java
modules/cesecore-common/src/org/cesecore/util/ui/DynamicUiActionCallback.java
modules/ejbca-ejb/src/org/ejbca/core/protocol/cmp/authentication/VerifyPKIMessage.java

Fixed minor typo

---

modules/ejbca-ejb-cli/src/org/ejbca/ui/cli/ra/FindEndEntityCommand.java

Correct FindEndEntityCommand help text
n/a

Correct FindEndEntityCommand help text

---

README.md

Updated the **EJBCA Installation** link in the README to docs.keyfactor.com (instead of doc.primekey.com). 
-

Update EJBCA Installation link in README to docs.keyfactor.com

---

modules/admin-gui/resources/languages/languagefile.fr.properties

Full update (and some fixes) of French Admin GUI, for v9.0.0, since v8.3.2.
Tested in Web GUI, when possible.

L10n: Admin GUI French update (based on 9.0.0) Fully translated

---

modules/ra-gui/resources/WEB-INF/classes/Messages_fr.properties

Full update of RA GUI French, for v9.0.0, since v8.3.2.
Fully tested in Web GUI.

L10n: RA GUI French update (based on 9.0.0) Fully translated
